name: Auto Update Profile

on:
  schedule:
    - cron: "0 */2 * * *" # jalan tiap 2 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Generate README
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: npm start

      - name: Commit & Push if changed
        run: |
          git config user.name "auto-profile"
          git config user.email "actions@github.com"
          if [[ `git status --porcelain README.md` ]]; then
            git add README.md
            git commit -m "auto: update profile [skip ci]"
            git push https://x-access-token:${{ secrets.API_KEY }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes detected"
          fi
